### ISSUE TITLE
Zip Files Stuck Loading

### ISSUE THREAD

**Issue by sudocoolcoder** [Alamantus/GooglePhotosExportOrganizer#10]
Hi @Alamantus while I am unzipping the loading bar is done but the zip files are still loading. I am on macOS and using version 1.1.1. The zip files are 103GB and the output file is 83GB. Please help ASAP. Thanks

**Comment by Alamantus** [comment]
@sudocoolcoder I'm going to close this issue as it is a duplicate of #9. Please see my comment requesting further information there.
