### ISSUE TITLE
Blank screen on startup

### ISSUE THREAD

**Issue by maxiride** [Alamantus/GooglePhotosExportOrganizer#3]
Hi, I found out about this tool from Reddit. As many I'm too looking around for a switch from Google Photo.

I've downloaded and extracted the program for Windows, but upon launch I am presented with a blank window as shown in the attachment. If there is anything else I can provide to help debug let me know.

https://i.imgur.com/vsDCJjD.png

**Comment by opa4h** [comment]
Hi!  I have a similar problem, only on mac os

**Comment by Alamantus** [comment]
Thanks for letting me know! I'll get this fixed as soon as possible and let you know when it's been updated.

**Comment by Alamantus** [comment]
@maxiride @opa4h I have uploaded new builds to the releases section that fix this problem. The files downloaded from the main site should be correct, so please try again.

And please submit another Issue if you run into any more problems!

**Comment by maxiride** [comment]
> 
> 
> @maxiride @opa4h I have uploaded new builds to the releases section that fix this problem. The files downloaded from the main site should be correct, so please try again.
> 
> And please submit another Issue if you run into any more problems!

That was fast! Thanks for the hotfix.
