### ISSUE TITLE
Error on launch — "The application “Google Photos Export Organizer” can’t be opened."

### ISSUE THREAD

**Issue by nreliu** [Alamantus/GooglePhotosExportOrganizer#4]
![image](https://user-images.githubusercontent.com/1503834/100657377-082cbc00-3303-11eb-8518-1b3eba535677.png)

I'm seeing this error when trying to launch the app on macOS Catalina 10.15.7.

**Comment by Alamantus** [comment]
@nreliu Thanks for letting me know! I've uploaded a new build to the releases page, and downloading from the [main page](https://alamantus.github.io/GooglePhotosExportOrganizer/) should give you a working copy now.

Please let me know if you still receive this message after trying again with a fresh download!

**Comment by nreliu** [comment]
Thanks for the quick fix! It looks like this bug has been squashed. 👍
